--- 
- hosts: cuckoo
  become: yes
  become_user: root
  vars:
  tasks:

    - name: Update cache
      apt:
        update_cache: yes
        cache_valid_time: 3600      

    - name: Upgrade packages
      apt: 
        upgrade: full

    - name: Install necessary packages
      apt:
        name: ['git','software-properties-common','vim','curl','tree','htop','python-pip','python','python-dev','libffi-dev','libssl-dev','python-virtualenv','python-setuptools','libjpeg-dev','zlib1g-dev','swig','mongodb','postgresql','libpq-dev','tcpdump','apparmor-utils','python-m2crypto']
        state: present

    - name: Tcpdump configuration
      shell: |
        groupadd pcap
        usermod -aG pcap kku
        chgrp pcap /usr/sbin/tcpdump
        setcap cap_net_raw,cap_net_admin=eip /usr/sbin/tcpdump

    - name: Install Volatility to do forensic on memory dumps
      shell: |
        cd ~
        git clone https://github.com/volatilityfoundation/volatility.git
        cd volatility
        python ./setup.py install

    - name: Install Distorm3 Powerful disassembler library for x86/AMD64
      shell: 
        sudo pip install distorm3
   
    - name: Add group for virtualbox
      group: 
        name: vboxusers
        state: present

    - name: Add user for cuckoo sandbox
      user: 
        name: cuckoo
        state: present
        groups: sudo,vboxusers

    - name: Add cuckoo user to virtualbox and KVM groups 
      shell: |
        usermod -aG vboxusers cuckoo
        #usermod -aG libvirtd kaku

    - name: Upgrade setuptools and cuckoo
      pip:
        name: ['setuptools','cuckoo','pip']
        state: latest

    - name: Create cuckoo working directory
      file:
        path: /opt/cuckoo
        state: directory
        owner: cuckoo
        group: cuckoo

    - name: Set cucko's working directory (cwd)
      shell: cuckoo --cwd /opt/cuckoo init

    - name: Download cuckoo signatures
      shell: cuckoo community

    - name: Enable mongodb
      shell: |
        sed -i '45d' /opt/cuckoo/conf/reporting.conf
        sed '/\[mongodb\]/a enabled = yes' /opt/cuckoo/conf/reporting.conf

    - name: Start the web interface
      shell: cuckoo web --host 0.0.0.0 --port 8080









    
